var language = [{
"name": "Name",
"email": "Email",
"phoneNumber": "Phone Number",
"codeActivation": "Code Activation",
"button":"Register",
"messageRequered": "Required Fields",
"messageEmail": "The email is not valid",
"noInternet": "No network connection detected",
"onSuccess" : "Successfully registered",
"onError" : "Unable to connect to the web service",
"twoDevices": "The application is registered in two devices, it will be activate as free version",
"badCodeActivation" : "Invalid activation code",
"errorUpdatePro": "Error registering the device",
"successUpdatePro" : "Device registered successfully",
"userRegistrated" : "The user is already registered"
},
{
"name": "Name",
"email": "Email",
"phoneNumber": "Phone Number",
"codeActivation": "Code Activation",
"button":"Register",
"messageRequered": "Required Fields",
"messageEmail": "The email is not valid",
"noInternet": "No network connection detected",
"onSuccess" : "Successfully registered",
"onError" : "Unable to connect to the web service",
"twoDevices": "The application is registered in two devices, it will be activate as free version",
"badCodeActivation" : "Invalid activation code",
"errorUpdatePro": "Error registering the device",
"successUpdatePro" : "Device registered successfully",
"userRegistrated" : "The user is already registered"
},
{
"name": "Name",
"email": "Email",
"phoneNumber": "Phone Number",
"codeActivation": "Code Activation",
"button":"Register",
"messageRequered": "Required Fields",
"messageEmail": "The email is not valid",
"noInternet": "No network connection detected",
"onSuccess" : "Successfully registered",
"onError" : "Unable to connect to the web service",
"twoDevices": "The application is registered in two devices, it will be activate as free version",
"badCodeActivation" : "Invalid activation code",
"errorUpdatePro": "Error registering the device",
"successUpdatePro" : "Device registered successfully",
"userRegistrated" : "The user is already registered"
},
{
"name": "Name",
"email": "Email",
"phoneNumber": "Phone Number",
"codeActivation": "Code Activation",
"button":"Register",
"messageRequered": "Required Fields",
"messageEmail": "The email is not valid",
"noInternet": "No network connection detected",
"onSuccess" : "Successfully registered",
"onError" : "Unable to connect to the web service",
"twoDevices": "The application is registered in two devices, it will be activate as free version",
"badCodeActivation" : "Invalid activation code",
"errorUpdatePro": "Error registering the device",
"successUpdatePro" : "Device registered successfully",
"userRegistrated" : "The user is already registered"
},
{
"name": "Nom",
"email": "Email",
"phoneNumber": "numéro de téléphone",
"codeActivation": "le code d'activation",
"button":"Inscrivez-vous",
"messageRequered": "Les champs obligatoires",
"messageEmail": "L'e-mail n'est pas valide",
"noInternet": "Pas de connexion Internet détectée",
"onSuccess" : "Enregistré avec succès",
"onError" : "Impossible de se connecter au service web",
"twoDevices": "La demande est enregistrée dans deux dispositifs activera aussi la version gratuite",
"badCodeActivation" : "Code d'activation invalide",
"errorUpdatePro": "Erreur enregistrer le dispositif",
"successUpdatePro" : "Dispositif enregistré avec succès",
"userRegistrated" : "L'utilisateur est déjà enregistré"
},
{
"name": "Nombre",
"email": "Correo Electronico",
"phoneNumber": "Numero de Telefono",
"codeActivation":"Codigo de Activación",
"button": "Registrarse",
"messageRequered": "Campos Requeridos",
"messageEmail": "El correo electronico no es valido",
"noInternet": "No se ha detectado conexion a Internet",
"onSuccess" : "Registro exitoso",
"onError" : "No se puede conectar al servicio web",
"twoDevices": "La aplicación ya está registrada en dos dispositivos, se activará como versión gratis",
"badCodeActivation" : "Código de activación no válido",
"errorUpdatePro": "Error registrando el dispositivo",
"successUpdatePro" : "Dispositivo registrado exitosamente",
"userRegistrated" : "El usuario ya está registrado"
},
{
"name": "Nome",
"email": "E-mail",
"phoneNumber": "número de telefone",
"codeActivation": "código de ativação",
"button": "Registrar",
"messageRequered": "Campos obrigatórios",
"messageEmail": "O e-mail não é válido",
"noInternet": "Sem conexão com a Internet detectada",
"onSuccess" : "Registrado com êxito",
"onError" : "Não é possível conectar ao serviço web",
"twoDevices": "A aplicação é registrado em dois dispositivos irá ativar a versão gratuita",
"badCodeActivation" : "Código de ativação inválido",
"errorUpdatePro": "Erro ao registrar o dispositivo",
"successUpdatePro" : "Dispositivo registrado com êxito",
"userRegistrated" : "O usuário já está registrado"
},
{
"name": "Name",
"email": "Email",
"phoneNumber": "Phone Number",
"codeActivation": "Code Activation",
"button":"Register",
"messageRequered": "Required Fields",
"messageEmail": "The email is not valid",
"noInternet": "No network connection detected",
"onSuccess" : "Successfully registered",
"onError" : "Unable to connect to the web service",
"twoDevices": "The application is registered in two devices, it will be activate as free version",
"badCodeActivation" : "Invalid activation code",
"errorUpdatePro": "Error registering the device",
"successUpdatePro" : "Device registered successfully",
"userRegistrated" : "The user is already registered"
},
{
"name": "Name",
"email": "Email",
"phoneNumber": "Phone Number",
"codeActivation": "Code Activation",
"button":"Register",
"messageRequered": "Required Fields",
"messageEmail": "The email is not valid",
"noInternet": "No network connection detected",
"onSuccess" : "Successfully registered",
"onError" : "Unable to connect to the web service",
"twoDevices": "The application is registered in two devices, it will be activate as free version",
"badCodeActivation" : "Invalid activation code",
"errorUpdatePro": "Error registering the device",
"successUpdatePro" : "Device registered successfully",
"userRegistrated" : "The user is already registered"
},
{
"name": "Name",
"email": "Email",
"phoneNumber": "Phone Number",
"codeActivation": "Code Activation",
"button":"Register",
"messageRequered": "Required Fields",
"messageEmail": "The email is not valid",
"noInternet": "No network connection detected",
"onSuccess" : "Successfully registered",
"onError" : "Unable to connect to the web service",
"twoDevices": "The application is registered in two devices, it will be activate as free version",
"badCodeActivation" : "Invalid activation code",
"errorUpdatePro": "Error registering the device",
"successUpdatePro" : "Device registered successfully",
"userRegistrated" : "The user is already registered"
}
]

